/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Carlos;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.LinkedList;
import java_cup.runtime.Symbol;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Carlos Bautista
 */
public class InterfazCompilador extends javax.swing.JFrame 
{
    FondoPanel fondo = new FondoPanel();
     

    /**
     * Creates new form InterfazCompilador
     */
    public InterfazCompilador() 
    {
        initComponents();
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        botonabrir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        abrir = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ResultSintax = new javax.swing.JTextArea();
        botonAnalizar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ResultadoLexic = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        botonAnalizar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comp++ ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonabrir.setBackground(new java.awt.Color(255, 255, 255));
        botonabrir.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        botonabrir.setForeground(new java.awt.Color(255, 255, 255));
        botonabrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder1.png"))); // NOI18N
        botonabrir.setText("ABRIR");
        botonabrir.setContentAreaFilled(false);
        botonabrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonabrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonabrir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder1.png"))); // NOI18N
        botonabrir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder2.png"))); // NOI18N
        botonabrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonabrirActionPerformed(evt);
            }
        });
        getContentPane().add(botonabrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 80, 80));

        abrir.setColumns(20);
        abrir.setRows(5);
        jScrollPane1.setViewportView(abrir);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, 180));

        ResultSintax.setColumns(20);
        ResultSintax.setRows(5);
        jScrollPane2.setViewportView(ResultSintax);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 270, 180));

        botonAnalizar.setBackground(new java.awt.Color(255, 255, 255));
        botonAnalizar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        botonAnalizar.setForeground(new java.awt.Color(255, 255, 255));
        botonAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/scan_research1.png"))); // NOI18N
        botonAnalizar.setText("A. LEXICO");
        botonAnalizar.setContentAreaFilled(false);
        botonAnalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAnalizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAnalizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/scan_research1.png"))); // NOI18N
        botonAnalizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/scan_research2.png"))); // NOI18N
        botonAnalizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnalizarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, 90));

        Borrar.setBackground(new java.awt.Color(255, 255, 255));
        Borrar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Borrar.setForeground(new java.awt.Color(255, 255, 255));
        Borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder_delete_deletefolder_1.png"))); // NOI18N
        Borrar.setText("LIMPIAR");
        Borrar.setContentAreaFilled(false);
        Borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Borrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder_delete_deletefolder_1.png"))); // NOI18N
        Borrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder_delete_deletefolder_2.png"))); // NOI18N
        Borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        getContentPane().add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 100, 90));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Compilador C++");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 760, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Carlos Bautista - Edgar Sánchez - Todos los derechos reservados");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 760, 29));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Resultado Análisis Sintáctico");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 270, -1));

        ResultadoLexic.setColumns(20);
        ResultadoLexic.setRows(5);
        jScrollPane3.setViewportView(ResultadoLexic);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 450, 180));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Resultado Analisis Lexico");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 430, -1));

        botonAnalizar2.setBackground(new java.awt.Color(255, 255, 255));
        botonAnalizar2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        botonAnalizar2.setForeground(new java.awt.Color(255, 255, 255));
        botonAnalizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/analysis1.png"))); // NOI18N
        botonAnalizar2.setText("A. SINTACTICO");
        botonAnalizar2.setContentAreaFilled(false);
        botonAnalizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAnalizar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAnalizar2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/analysis1.png"))); // NOI18N
        botonAnalizar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/analysis2.png"))); // NOI18N
        botonAnalizar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAnalizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnalizar2ActionPerformed(evt);
            }
        });
        getContentPane().add(botonAnalizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 140, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonabrirActionPerformed
        // TODO add your handling code here:
          int iResp;
        String strTexto= null;
        ArrayList<String> alLinea=null;
        FileExplorer fmLeeArchivo=null;
        
        try
        {
            iResp=jFileChooser1.showOpenDialog(this);
            if (iResp==jFileChooser1.APPROVE_OPTION) {
                
                fmLeeArchivo = new FileExplorer();
                alLinea=fmLeeArchivo.leeArchivo(jFileChooser1.getSelectedFile().toString());
                if (alLinea.size()>0) 
                {
                    
                    for (int i = 0; i < alLinea.size(); i++) 
                    {
                        
                        strTexto=(String)alLinea.get(i);
                        abrir.append(strTexto+ "\n");
                        
                    }
                    
                }
               
                
            }
            
        }catch (Exception ex) 
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botonabrirActionPerformed

    private void botonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalizarActionPerformed
        // TODO add your handling code here:
        
        try
        {
            probarLexer();
        }
        
        catch(IOException ex)
        {
            System.out.println(ex.getMessage());
                    
        }
        
    }//GEN-LAST:event_botonAnalizarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
        ResultSintax.setText(null);
        abrir.setText(null);
       ResultadoLexic.setText(null);
    }//GEN-LAST:event_BorrarActionPerformed

    private void botonAnalizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalizar2ActionPerformed
        // TODO add your handling code here:
        
        File fichero= new File("codigo.txt");
        BufferedWriter writer;
        try{
            writer = new BufferedWriter(new FileWriter(fichero));
            writer.write(ResultSintax.getText());
            writer.close();
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(null, "No se pudo guardar archivo de entrada debido a "+ ex.toString());
        }

        try{
            //probamos nuestra clase Lexer2.java
            probarLexerFile();
        }
        catch(IOException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_botonAnalizar2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new InterfazCompilador().setVisible(true);
                /*Principal window = new Principal();
					window.frmTrabajoDeCompiladores.setLocationRelativeTo(null);
					window.frmTrabajoDeCompiladores.setVisible(true);*/
            }
        });
    }
    
    //-------------------------- Para fondo -------------------------------------
    class FondoPanel extends JPanel
        {
            private Image imagen;
            
                public void paint (Graphics g)
                {
                    imagen = new ImageIcon(getClass().getResource("/Imagenes/FONDOCISCO.png")).getImage();
                    
                    g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
                    
                    setOpaque(false);
                    
                    super.paint(g);
                    
                }
            
            
        }
    //--------------------------------------------------------------------------
    
  
    //--------------------- lexer sintactico -----------------------------------
    
     public void probarLexerFile() throws IOException
     {
        Reader reader = new BufferedReader(new FileReader("codigo.txt"));
        LexerSintax lexer = new LexerSintax (reader);
        while(true)
        {
            SintacticTokens token = lexer.yylex();
            if(token==null)
            {
                ResultSintax.setText(ResultSintax.getText()+"Analisis realizado correctamente"+"\n");
                //System.out.println("EOF");
                return;
            }
            
            switch(token)
            {
                case Digito:
                    ResultSintax.setText(ResultSintax.getText()+"Token Numeros:" +lexer.lexeme+"\n");
                    //System.out.println("TOKEN: "+token+" "+lexer.lexeme);
                break;
                     case String:
                    ResultSintax.setText(ResultSintax.getText()+"Token Palabras:"+lexer.lexeme+"\n");
                    //System.out.println("TOKEN: "+token+" "+lexer.lexeme);
                break;
                    
                    
                    
                default:
                    ResultSintax.setText(ResultSintax.getText()+"SINTACTICO: "+token+"\n");
                    //System.out.println("TOKEN: "+token);
            }
        }
    }
     
    //------------------------------------------------------------------------------
     
     
    //---------------------- lexer LEXICO ------------------------------------------- 
    public void probarLexer() throws IOException
    {
        review  c= new review ();
        
        File fichero = new File("fichero.txt");
        PrintWriter Writer;
           
        
        try 
        {
            Writer = new PrintWriter(fichero);
               Writer.print(abrir.getText());
                  Writer.close();
            
        } 
        
        catch(FileNotFoundException ex)
        {
           // Logger.getLogger(InterfazCompilador.class.getName()).log(Level.SEVERE,null,ex);
            
        }
        
        Reader reader;
        reader = new BufferedReader(new FileReader("fichero.txt"));
        LexerFlex lexer = new LexerFlex(reader);
        
        String Resultado="";
        
        while(true)
        {
            Token tok= lexer.yylex();
            
            if (tok == null) 
            {
                
                Resultado = Resultado+"FIN";
                ResultadoLexic.setText(Resultado);
                return ;
            }
            
            switch(tok)
            {
                case ERROR:
                    Resultado = Resultado+"ERROR LEXICO: "+lexer.lexeme+" "+" "+" Linea: "
                            + c.linea+"\n";
                    break;
                case CADENA: case NUM:
                    Resultado = Resultado+"LEXEMA: "+tok+" "+" "+" "+" "+" TOKENS: "+lexer.lexeme+"\n";
                    break;
                default: 
                    Resultado = Resultado+"LEXEMA: "+tok+" "+" "+" "+" "+" TOKENS: "+lexer.lexeme+"\n";
                    break;
            }
                    
        } 
    } 
    
    
    //----------------------- Para ejecutar .exe ------------------------------- 
      public static void Ejecutar()
    {
        String comand= "C:\\Users\\TeamIT\\Documents\\NetBeansProjects\\AnalizadorSintactico\\src\\CODGEN\\Hola_Mundo.exe";
            Runtime p= Runtime.getRuntime();
        try 
        {
            p.exec(comand);
        } 
        catch (Exception e) 
        {
            System.out.println( e.getMessage() );
    
        }
    }
    //-------------------------------------------------------------------------- 
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JTextArea ResultSintax;
    private javax.swing.JTextArea ResultadoLexic;
    private javax.swing.JTextArea abrir;
    private javax.swing.JButton botonAnalizar;
    private javax.swing.JButton botonAnalizar2;
    private javax.swing.JButton botonabrir;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
